### PR TITLE
Collaboration and jest

### PR DESCRIPTION
**Pull request by msducheminjr**
I wanted to collaborate on this project.

I tried to make some fixes, but I got stuck in a couple of places. I need a peer review on this and left some of the modifications I wanted unfinished. Can you collaborate with me to improve this Lightning Web Component?

### CODE REVIEW

**Comment by msducheminjr** [comment]
I didn't really understand the `:host` properties in the CSS file. Could you explain to me what they do?

**Review by sripadaa555 — APPROVED** [review]
Hello Michael,

Thank you so much for reviewing my code and taking initiative to provide the right changes. I understand that my HTML code has had a few inconsistencies with respect to the naming convention. I will make note of this and be careful the next time I code. 

Once again thank you :)

**Review by sripadaa555 — COMMENTED** [review]
I have added the lightning_Apppage as a target in order to allow this LWC to show on the lightning application page upon adding the component.

**Comment by sripadaa555** [comment]
> I didn't really understand the `:host` properties in the CSS file. Could you explain to me what they do?

Hello Micheal,

The :host properties in the CSS file would come into the picture when we have child components as well. I initially wanted to have the text area and a separate result section but then went ahead with just one component..... If we wanted to style the root element instead of any child component elements then :host properties would be useful. I understand in my code I can get rid of it and directly use the HTML tags only. I will work on those changes in the future.

**Comment by sripadaa555** [comment]
For the Jest testing:

Thank you so much for letting me think in the direction of testing. I have gone through the below trailhead link and refactored the code to handle async updates and use Promise. I have created an additional test case as well. Please feel free to let me know in case of any changes or errors. 

https://trailhead.salesforce.com/content/learn/modules/test-lightning-web-components/write-a-jest-test

Thank you!!

**Comment by msducheminjr** [comment]
> Thank you so much for letting me think in the direction of testing. I have gone through the below trailhead link and refactored the code to handle async updates and use Promise. I have created an additional test case as well. Please feel free to let me know in case of any changes or errors.

Thank you for taking the effort to collaborate on this. I'm really enjoying the interaction and the effort.

 When I run the current master using `npm run test:unit` the current code has a syntax error. (It's missing the `});` on line 53 to close the `describe` block that the `it` statements are nested in.).

These are the results I get after fixing the syntax error:

### First test 
(problem is in line 21)
```bash
   TypeError: Cannot read property 'textContent' of null

      20 |        return Promise.resolve().then(() => {
      21 |     const charSpan = element.querySelector("span[data-recid=char]");
    > 22 |     expect(charSpan.textContent).toBe('0');
         |                     ^
      23 |              });
      24 |
      25 |   });
```

### Second test
(problem is in line 41)
```bash
 TypeError: Cannot set property 'value' of null

      40 |   document.body.appendChild(element);
      41 |   const test_input=element.shadowRoot.querySelector('textarea');
    > 42 |   test_input.value='Extra credit';
         |                   ^
      43 |   test_input.dispatchEvent(new CustomEvent('change'));
      44 |   return Promise.resolve().then(() => {
      45 |     expect(element.shadowRoot.querySelector("span[data-recid=word]").textContent).toBe(2);

      at Object.<anonymous> (force-app/main/default/lwc/wordCounterLive/__tests__/wordCounterLive.test.js:42:19)
```

**Pull request merged**
